# Generated by Django 6.0.6 on 2026-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled_by_client', 'Cancelled by Client'), ('cancelled_by_practitioner', 'Cancelled by Practitioner')], default='pending', max_length=30),
        ),
    ]
